namespace Domain
{
    public interface IAmazonJewelryDataFeedItem
    {
        //requied
         string? feed_product_type { get; set; }
         string? item_sku { get; set; }
         string? brand_name { get; set; }
         string? external_product_id { get; set; }
         string? external_product_id_type { get; set; }
         string? item_name { get; set; }
         string? item_length_numeric { get; set; }
         string? item_length_numeric_unit_of_measure { get; set; }
         string? main_image_url { get; set; }
         string? target_gender { get; set; }
         string? quantity { get; set; }
         string? standard_price { get; set; }
         string? item_type { get; set; }
         string? metal_type { get; set; }
         string? material_type1 { get; set; }
         string? material_type2 { get; set; }
         string? material_type3 { get; set; }
         string? department_name { get; set; }
         string? gem_type1 { get; set; }
         string? gem_type2 { get; set; }
         string? gem_type3 { get; set; }
         string? product_description { get; set; }
         string? generic_keywords { get; set; }
         string? bullet_point1 { get; set; }
         string? bullet_point2 { get; set; }
         string? bullet_point3 { get; set; }
         string? bullet_point4 { get; set; }
         string? bullet_point5 { get; set; }
         string? bullet_point6 { get; set; }
         string? bullet_point7 { get; set; }
         string? bullet_point8 { get; set; }
         string? bullet_point9 { get; set; }
         string? bullet_point10 { get; set; }
         string? supplier_declared_dg_hz_regulation1 { get; set; }
         string? supplier_declared_dg_hz_regulation2 { get; set; }
         string? supplier_declared_dg_hz_regulation3 { get; set; }
         string? supplier_declared_dg_hz_regulation4 { get; set; }
         string? supplier_declared_dg_hz_regulation5 { get; set; }
         string? color_name { get; set; }
         string? part_number { get; set; }
         string? item_type_name { get; set; }
         string? size_name { get; set; }
         string? lifecycle_supply_type { get; set; }
         string? country_of_origin { get; set; }
         string? cpsia_cautionary_statement1 { get; set; }
         string? cpsia_cautionary_statement2 { get; set; }
         string? cpsia_cautionary_statement3 { get; set; }
         string? cpsia_cautionary_statement4 { get; set; }
         string? supplier_declared_material_regulation1 { get; set; }
         string? supplier_declared_material_regulation2 { get; set; }
         string? supplier_declared_material_regulation3 { get; set; }
         string? map_price { get; set; }
         string? currency { get; set; }
         string? condition_type { get; set; }
         string? ring_size { get; set; }
         string? color_map { get; set; }
         string? age_range_description { get; set; }
        //Images
         string? other_image_url1 { get; set; }
         string? other_image_url2 { get; set; }
         string? other_image_url3 { get; set; }
         string? other_image_url4 { get; set; }
         string? other_image_url5 { get; set; }
         string? other_image_url6 { get; set; }
         string? other_image_url7 { get; set; }
         string? other_image_url8 { get; set; }
         string? swatch_image_url { get; set; }
         string? pt8_image_url { get; set; }
         string? pt7_image_url { get; set; }
         string? pt5_image_url { get; set; }
         string? pt4_image_url { get; set; }
         string? pt3_image_url { get; set; }
         string? pt2_image_url { get; set; }
         string? pt6_image_url { get; set; }
         string? pt1_image_url { get; set; }
        //Variation 
         string? relationship_type { get; set; }
         string? variation_theme { get; set; }
         string? package_level { get; set; }
         string? parent_sku { get; set; }
         string? package_contains_quantity { get; set; }
         string? package_contains_identifier { get; set; }
         string? parent_child { get; set; }
        // basic
         string? update_delete { get; set; }
         string? certificate_number { get; set; }
         string? model { get; set; }
         string? grade_rating { get; set; }
         string? manufacturer { get; set; }
         string? certificate_type { get; set; }
         string? production_method { get; set; }
         string? closure_type { get; set; }
         string? model_name { get; set; }
         string? care_instructions { get; set; }
        //discovery
         string? stone_color1 { get; set; }
         string? stone_color2 { get; set; }
         string? stone_color3 { get; set; }
         string? style_name { get; set; }
         string? metals_metal_weight_unit_of_measure { get; set; }
         string? stones_color { get; set; }
         string? occasion_type1 { get; set; }
         string? occasion_type2 { get; set; }
         string? occasion_type3 { get; set; }
         string? occasion_type4 { get; set; }
         string? occasion_type5 { get; set; }
         string? clasp_type { get; set; }
         string? stones_id { get; set; }
         string? stones_creation_method { get; set; }
         string? athlete { get; set; }
         string? team_name { get; set; }
         string? stone_shape1 { get; set; }
         string? stone_shape2 { get; set; }
         string? stone_shape3 { get; set; }
         string? stone_clarity1 { get; set; }
         string? stone_clarity2 { get; set; }
         string? stone_clarity3 { get; set; }
         string? collection_name { get; set; }
         string? metals_metal_weight { get; set; }
         string? metals_metal_type { get; set; }
         string? stones_type { get; set; }
         string? stones_clarity { get; set; }
         string? stones_number_of_stones { get; set; }
         string? stones_treatment_method { get; set; }
         string? fur_description { get; set; }
         string? setting_type { get; set; }
         string? metals_id { get; set; }
         string? initial_character { get; set; }
         string? metals_metal_stamp { get; set; }
         string? stones_shape { get; set; }
         string? chain_length_unit { get; set; }
         string? stones_cut { get; set; }
         string? stone_cut1 { get; set; }
         string? stone_cut2 { get; set; }
         string? stone_cut3 { get; set; }
         string? league_name { get; set; }
         string? thesaurus_subject_keywords { get; set; }
         string? chain_length_derived { get; set; }
         string? chain_type { get; set; }
         string? item_booking_date { get; set; }
         string? style_keywords1 { get; set; }
         string? style_keywords2 { get; set; }
         string? style_keywords3 { get; set; }
         string? is_resizable { get; set; }
         string? back_finding { get; set; }
         string? stone_creation_method1 { get; set; }
         string? stone_creation_method2 { get; set; }
         string? stone_creation_method3 { get; set; }
         string? stone_treatment_method1 { get; set; }
         string? stone_treatment_method2 { get; set; }
         string? stone_treatment_method3 { get; set; }
         string? pattern_name { get; set; }
         string? embellishment_feature { get; set; }
         string? drop_length_unit { get; set; }
         string? drop_length { get; set; }
         string? band_thickness { get; set; }
         string? band_thickness_unit_of_measure { get; set; }
         string? theme { get; set; }
         string? is_autographed { get; set; }
         string? sport_type1 { get; set; }
         string? sport_type2 { get; set; }
         string? seasons1 { get; set; }
         string? seasons2 { get; set; }
         string? seasons3 { get; set; }
         string? seasons4 { get; set; }
         string? lifestyle { get; set; }
         string? fit_type1 { get; set; }
         string? fit_type2 { get; set; }
         string? fit_type3 { get; set; }
         string? fit_type4 { get; set; }
         string? fit_type5 { get; set; }
         string? weave_type { get; set; }
         string? special_size_type { get; set; }
        //Product Enrichmen
         string? pearl_type { get; set; }
         string? legal_compliance_certification_certifying_authority_name { get; set; }
         string? pearl_uniformity { get; set; }
         string? pearl_shape { get; set; }
         string? pearl_surface_blemishes { get; set; }
         string? pearl_lustre { get; set; }
         string? legal_compliance_certification_geographic_jurisdiction { get; set; }
         string? flash_point_unit_of_measure { get; set; }
         string? pearl_stringing_method { get; set; }
         string? pearl_minimum_color { get; set; }
         string? inscription { get; set; }
         string? number_of_pearls { get; set; }
         string? index_suppressed { get; set; }
         string? number_of_stones { get; set; }
         string? ring_sizing_lower_range { get; set; }
         string? ring_sizing_upper_range { get; set; }
         string? duration_unit_of_measure { get; set; }
         string? subject_character { get; set; }
         string? duration { get; set; }
         string? sub_brand_name { get; set; }
         string? sleeve_type { get; set; }
         string? fabric_wash { get; set; }
         string? finish_type1 { get; set; }
         string? finish_type2 { get; set; }
        //Dimensions kích thước trọng lượng
         string? item_display_weight { get; set; }
         string? total_diamond_weight { get; set; }
         string? item_display_diameter { get; set; }
         string? stone_weight1 { get; set; }
         string? stone_weight2 { get; set; }
         string? stone_weight3 { get; set; }
         string? stone_weight_unit_of_measure1 { get; set; }
         string? stone_weight_unit_of_measure2 { get; set; }
         string? stone_weight_unit_of_measure3 { get; set; }
         string? total_gem_weight { get; set; }
         string? size_per_pearl { get; set; }
         string? unit_count { get; set; }
         string? item_display_diameter_unit_of_measure { get; set; }
         string? item_display_length { get; set; }
         string? item_display_length_unit_of_measure { get; set; }
         string? total_gem_weight_unit_of_measure { get; set; }
         string? item_display_weight_unit_of_measure { get; set; }
         string? total_diamond_weight_unit_of_measure { get; set; }
         string? unit_count_type { get; set; }
         string? item_width_unit_of_measure { get; set; }
         string? item_width { get; set; }
         string? item_height { get; set; }
         string? size_map { get; set; }
         string? item_height_unit_of_measure { get; set; }
         string? item_length_unit_of_measure { get; set; }
         string? item_length { get; set; }
         string? item_display_width { get; set; }
         string? website_shipping_weight { get; set; }
         string? website_shipping_weight_unit_of_measure { get; set; }
         string? stone_height1 { get; set; }
         string? stone_height2 { get; set; }
         string? stone_height3 { get; set; }
         string? stone_length1 { get; set; }
         string? stone_length2 { get; set; }
         string? stone_length3 { get; set; }
         string? stone_width1 { get; set; }
         string? stone_width2 { get; set; }
         string? stone_width3 { get; set; }
         string? stone_dimensions_unit_of_measure1 { get; set; }
         string? stone_dimensions_unit_of_measure2 { get; set; }
         string? stone_dimensions_unit_of_measure3 { get; set; }
         string? item_display_height_unit_of_measure { get; set; }
         string? item_display_width_unit_of_measure { get; set; }
         string? item_display_height { get; set; }
         string? stone_width_unit_of_measure1 { get; set; }
         string? stone_width_unit_of_measure2 { get; set; }
         string? stone_width_unit_of_measure3 { get; set; }
         string? stone_length_unit_of_measure1 { get; set; }
         string? stone_length_unit_of_measure2 { get; set; }
         string? stone_length_unit_of_measure3 { get; set; }
         string? total_metal_weight { get; set; }
         string? total_metal_weight_unit_of_measure { get; set; }
         string? item_shape { get; set; }
        //Fulfillment quy trình thực hiện đơn hàng
         string? package_length { get; set; }
         string? package_weight_unit_of_measure { get; set; }
         string? package_height { get; set; }
         string? fulfillment_center_id { get; set; }
         string? package_length_unit_of_measure { get; set; }
         string? package_height_unit_of_measure { get; set; }
         string? package_width { get; set; }
         string? package_width_unit_of_measure { get; set; }
         string? package_weight { get; set; }
        //Compliance các tuân thủ về hàng hóa tại các quốc gia
         string? regulation_type1 { get; set; }
         string? regulation_type2 { get; set; }
         string? regulation_type3 { get; set; }
         string? regulation_type4 { get; set; }
         string? regulation_type5 { get; set; }
         string? regulatory_compliance_certification_value1 { get; set; }
         string? regulatory_compliance_certification_value2 { get; set; }
         string? regulatory_compliance_certification_value3 { get; set; }
         string? regulatory_compliance_certification_value4 { get; set; }
         string? regulatory_compliance_certification_value5 { get; set; }
         string? batteries_required { get; set; }
         string? are_batteries_included { get; set; }
         string? battery_cell_composition { get; set; }
         string? battery_type1 { get; set; }
         string? battery_type2 { get; set; }
         string? battery_type3 { get; set; }
         string? number_of_batteries1 { get; set; }
         string? number_of_batteries2 { get; set; }
         string? number_of_batteries3 { get; set; }
         string? battery_weight { get; set; }
         string? battery_weight_unit_of_measure { get; set; }
         string? number_of_lithium_metal_cells { get; set; }
         string? number_of_lithium_ion_cells { get; set; }
         string? lithium_battery_packaging { get; set; }
         string? lithium_battery_energy_content { get; set; }
         string? lithium_battery_energy_content_unit_of_measure { get; set; }
         string? lithium_battery_weight { get; set; }
         string? lithium_battery_weight_unit_of_measure { get; set; }
         string? hazmat_united_nations_regulatory_id { get; set; }
         string? safety_data_sheet_url { get; set; }
         string? item_weight { get; set; }
         string? item_weight_unit_of_measure { get; set; }
         string? item_volume { get; set; }
         string? item_volume_unit_of_measure { get; set; }
         string? warranty_type { get; set; }
         string? legal_compliance_certification_expiration_date { get; set; }
         string? legal_compliance_certification_regulatory_organization_name { get; set; }
         string? legal_compliance_certification_status { get; set; }
         string? flash_point { get; set; }
         string? warranty_description { get; set; }
         string? legal_compliance_certification_date_of_issue { get; set; }
         string? legal_compliance_certification_metadata { get; set; }
         string? legal_compliance_certification_value { get; set; }
         string? metal_stamp { get; set; }
         string? ghs_classification_class1 { get; set; }
         string? ghs_classification_class2 { get; set; }
         string? ghs_classification_class3 { get; set; }
         string? california_proposition_65_compliance_type { get; set; }
         string? california_proposition_65_chemical_names1 { get; set; }
         string? california_proposition_65_chemical_names2 { get; set; }
         string? california_proposition_65_chemical_names3 { get; set; }
         string? california_proposition_65_chemical_names4 { get; set; }
         string? california_proposition_65_chemical_names5 { get; set; }
         string? pesticide_marking_type1 { get; set; }
         string? pesticide_marking_type2 { get; set; }
         string? pesticide_marking_type3 { get; set; }
         string? pesticide_marking_registration_status1 { get; set; }
         string? pesticide_marking_registration_status2 { get; set; }
         string? pesticide_marking_registration_status3 { get; set; }
         string? pesticide_marking_certification_number1 { get; set; }
         string? pesticide_marking_certification_number2 { get; set; }
         string? pesticide_marking_certification_number3 { get; set; }
         string? fcc_radio_frequency_emission_compliance_registration_status { get; set; }
         string? fcc_radio_frequency_emission_compliance_point_of_contact_email { get; set; }
         string? fcc_radio_frequency_emission_compliance_point_of_contact_phone_number { get; set; }
         string? fcc_radio_frequency_emission_compliance_point_of_contact_name { get; set; }
         string? fcc_radio_frequency_emission_compliance_identification_number { get; set; }
         string? fcc_radio_frequency_emission_compliance_point_of_contact_address { get; set; }
         string? fabric_type { get; set; }
         string? import_designation { get; set; }
        //Offer - các thuộc tính để làm măt hàng này có thể bán được
         string? merchant_release_date { get; set; }
         string? list_price { get; set; }
         string? restock_date { get; set; }
         string? number_of_items { get; set; }
         string? fulfillment_latency { get; set; }
         string? offering_can_be_giftwrapped { get; set; }
         string? item_package_quantity { get; set; }
         string? offering_end_date { get; set; }
         string? max_order_quantity { get; set; }
         string? merchant_shipping_group_name { get; set; }
         string? offering_start_date { get; set; }
         string? product_tax_code { get; set; }
         string? offering_can_be_gift_messaged { get; set; }
         string? condition_note { get; set; }
         string? sale_price { get; set; }
         string? sale_from_date { get; set; }
         string? sale_end_date { get; set; }
         string? product_site_launch_date { get; set; }
        //B2B
         string? business_price { get; set; }
         string? quantity_price_type { get; set; }
         string? quantity_lower_bound1 { get; set; }
         string? quantity_price1 { get; set; }
         string? quantity_lower_bound2 { get; set; }
         string? quantity_price2 { get; set; }
         string? quantity_lower_bound3 { get; set; }
         string? quantity_price3 { get; set; }
         string? quantity_lower_bound4 { get; set; }
         string? quantity_price4 { get; set; }
         string? quantity_lower_bound5 { get; set; }
         string? quantity_price5 { get; set; }
         string? progressive_discount_type { get; set; }
         string? progressive_discount_lower_bound1 { get; set; }
         string? progressive_discount_value1 { get; set; }
         string? progressive_discount_lower_bound2 { get; set; }
         string? progressive_discount_value2 { get; set; }
         string? progressive_discount_lower_bound3 { get; set; }
         string? progressive_discount_value3 { get; set; }
         string? national_stock_number { get; set; }
         string? unspsc_code { get; set; }
         string? pricing_action { get; set; }
    }
}