// <auto-generated />
using System;
using AmazonIntegrationDataApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmazonIntegrationDataApi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240104032536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmazonIntegrationDataApi.Models.AmazonJewelryDataFeedItemV3", b =>
                {
                    b.Property<string>("item_sku")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("age_range_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("are_batteries_included")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("athlete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("authenticated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("back_finding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_length_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_material_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_size_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_size_num_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_thickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_thickness_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("band_width_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("batteries_required")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("battery_cell_composition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("battery_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("battery_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("battery_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("battery_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("battery_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("belt_style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("belt_width_derived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("belt_width_string")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("belt_width_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bezel_function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bezel_material_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brightness_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bullet_point9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("business_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calendar_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("california_proposition_65_chemical_names1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("california_proposition_65_chemical_names2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("california_proposition_65_chemical_names3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("california_proposition_65_chemical_names4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("california_proposition_65_chemical_names5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("california_proposition_65_compliance_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("care_instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("case_diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("case_diameter_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("case_material_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("case_thickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("case_thickness_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catalog_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_number9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("certificate_type9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chain_length_derived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chain_length_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chain_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clasp_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("closure_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("collection_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color_map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compatible_devices")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condition_note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condition_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("connectivity_protocol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("controller_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_as_labeled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpsia_cautionary_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpsia_cautionary_statement1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpsia_cautionary_statement2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpsia_cautionary_statement3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpsia_cautionary_statement4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("delivery_schedule_group_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department_name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department_name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department_name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department_name4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department_name5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depth_front_to_back")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depth_front_to_back_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depth_height_floor_to_top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depth_height_floor_to_top_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depth_width_side_to_side")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depth_width_side_to_side_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dial_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dial_window_material_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("directions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("display_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("drop_length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("drop_length_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embellishment_feature1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embellishment_feature2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embellishment_feature3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embellishment_feature4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("embellishment_feature5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("energy_guide_annual_operating_cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("energy_guide_cost_disclosure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("external_product_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("external_product_id_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_type9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fabric_wash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fc_shelf_life")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fc_shelf_life_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcc_radio_frequency_emission_compliance_identification_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcc_radio_frequency_emission_compliance_point_of_contact_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcc_radio_frequency_emission_compliance_point_of_contact_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcc_radio_frequency_emission_compliance_point_of_contact_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcc_radio_frequency_emission_compliance_point_of_contact_phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcc_radio_frequency_emission_compliance_registration_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feed_product_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("finish_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("finish_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fit_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fit_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fit_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fit_type4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fit_type5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flash_point")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flash_point_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("front_style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fulfillment_center_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fulfillment_latency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fur_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gauge_derived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gem_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gem_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gem_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("generic_keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghs_classification_class1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghs_classification_class2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghs_classification_class3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("golf_club_flex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grade_rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gtin_exemption_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("handle_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hazmat_united_nations_regulatory_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horsepower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horsepower_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("import_designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("included_components1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("included_components2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("included_components3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("included_components4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("included_components5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("index_suppressed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("initial_character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inner_material_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insulation_resistance_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_assembly_required")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_autographed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_discontinued_by_manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_expiration_dated_product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_oem_authorized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_resizable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_booking_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_diameter_derived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_diameter_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_diameter_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_height_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_length_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_display_width_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_height_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_length_numeric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_length_numeric_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_length_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_package_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_pitch_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_shape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_thickness_derived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_thickness_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_torque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_torque_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_type_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_volume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_volume_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_width_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("league_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leg_diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leg_diameter_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leg_style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_certifying_authority_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_date_of_issue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_expiration_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_geographic_jurisdiction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_regulatory_organization_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal_compliance_certification_value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lifecycle_supply_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lifestyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("light_source_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line_size_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lining_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("list_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lithium_battery_energy_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lithium_battery_energy_content_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lithium_battery_packaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lithium_battery_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lithium_battery_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("main_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("map_policy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("map_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material_composition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material_type4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material_type5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("max_aggregate_ship_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("max_order_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maximum_operating_pressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maximum_operating_pressure_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maximum_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maximum_size_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maximum_weight_recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maximum_weight_recommendation_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("measurement_system")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("merchant_release_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("merchant_shipping_group_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metal_stamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metal_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metals_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metals_metal_stamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metals_metal_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metals_metal_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metals_metal_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model_year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mounting_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("national_stock_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("neck_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("neck_size_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("neck_style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_batteries1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_batteries2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_batteries3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_boxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_compartments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_drawers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_items")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_lithium_ion_cells")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_lithium_metal_cells")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_pearls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_pieces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_stones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_teeth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number_of_wheels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occasion_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occasion_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occasion_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occasion_type4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("occasion_type5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oem_equivalent_part_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("offering_can_be_gift_messaged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("offering_can_be_giftwrapped")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("offering_end_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("offering_start_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opacity_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operating_system")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other_image_url8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("outer_material_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("outer_material_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("outer_material_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("outer_material_type4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("outer_material_type5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_contains_identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_contains_quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_height_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_length_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_width_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paint_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paper_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paper_size_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parent_child")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parent_sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("part_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pattern_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pattern_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pearl_lustre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pearl_minimum_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pearl_shape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pearl_stringing_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pearl_surface_blemishes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pearl_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pearl_uniformity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_certification_number1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_certification_number2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_certification_number3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_registration_status1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_registration_status2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_registration_status3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesticide_marking_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platinum_keywords1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platinum_keywords2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platinum_keywords3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platinum_keywords4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platinum_keywords5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pocket_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("power_source_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pricing_action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_expiration_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_site_launch_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_tax_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("production_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progressive_discount_lower_bound1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progressive_discount_lower_bound2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progressive_discount_lower_bound3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progressive_discount_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progressive_discount_value1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progressive_discount_value2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("progressive_discount_value3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt1_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt2_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt3_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt4_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt5_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt6_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt7_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pt8_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_lower_bound1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_lower_bound2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_lower_bound3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_lower_bound4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_lower_bound5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_price1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_price2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_price3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_price4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_price5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity_price_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("recommended_uses_for_product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulation_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulation_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulation_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulation_type4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulation_type5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulatory_compliance_certification_value1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulatory_compliance_certification_value2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulatory_compliance_certification_value3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulatory_compliance_certification_value4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regulatory_compliance_certification_value5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relationship_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resale_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("restock_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ring_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ring_sizing_lower_range")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ring_sizing_upper_range")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("safety_data_sheet_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sale_end_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sale_from_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sale_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seasons1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seasons2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seasons3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seasons4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("setting_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shaft_style_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shank_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shoe_width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shoe_width_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size_map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size_per_pearl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sleeve_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("special_features1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("special_features2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("special_features3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("special_features4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("special_features5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("special_size_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specific_uses_for_product1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specific_uses_for_product2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specific_uses_keywords1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specific_uses_keywords2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specific_uses_keywords3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specific_uses_keywords4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specific_uses_keywords5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("speed_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport_type1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport_type2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport_type3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("standard_price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_clarity1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_clarity2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_clarity3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_color1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_color2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_color3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_creation_method1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_creation_method2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_creation_method3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_cut1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_cut2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_cut3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_dimensions_unit_of_measure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_dimensions_unit_of_measure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_dimensions_unit_of_measure3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_height1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_height2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_height3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_length1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_length2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_length3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_length_unit_of_measure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_length_unit_of_measure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_length_unit_of_measure3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_shape1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_shape2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_shape3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_treatment_method1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_treatment_method2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_treatment_method3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_weight1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_weight2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_weight3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_weight_unit_of_measure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_weight_unit_of_measure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_weight_unit_of_measure3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_width1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_width2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_width3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_width_unit_of_measure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_width_unit_of_measure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stone_width_unit_of_measure3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_clarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_creation_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_cut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_number_of_stones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_shape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_treatment_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stones_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strap_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("style_keywords1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("style_keywords2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("style_keywords3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("style_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sub_brand_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject_character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_dg_hz_regulation1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_dg_hz_regulation2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_dg_hz_regulation3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_dg_hz_regulation4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_dg_hz_regulation5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_material_regulation1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_material_regulation2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_declared_material_regulation3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supported_application")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("swatch_image_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_base1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_base2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_base3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_base4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_base5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_keywords1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_keywords2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_keywords3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_keywords4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_audience_keywords5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("team_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_attribute_keywords1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_attribute_keywords2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_attribute_keywords3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_attribute_keywords4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_attribute_keywords5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_subject_keywords1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_subject_keywords2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_subject_keywords3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_subject_keywords4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thesaurus_subject_keywords5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_diamond_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_diamond_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_gem_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_gem_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_metal_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_metal_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("underwire_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_count_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unspsc_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_delete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("variation_theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voltage_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("waist_size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("waist_size_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warranty_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warranty_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("watch_movement_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("water_resistance_depth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("water_resistance_depth_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("water_resistance_level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weave_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website_shipping_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website_shipping_weight_unit_of_measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wheel_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("item_sku");

                    b.ToTable("AmazonJewelryDataFeedItems");
                });

            modelBuilder.Entity("AmazonIntegrationDataApi.Models.ValidValueVsiriusModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ValidValueVsiriusModels");
                });
#pragma warning restore 612, 618
        }
    }
}
