using AmazonIntegrationDataApi.Dtos;
using AmazonIntegrationDataApi.Models;

namespace AmazonIntegrationDataApi.Helpers.MapVSiriusDBToAmazonDB
{
    public static class Filters
    {
        public static List<AmazonJewelryDataFeedItemV3_Dto> filtersSKU(List<AmazonJewelryDataFeedItemV3_Dto> input) 
        {
            return input.Where(amazon =>
                amazon.main_image_url != null
                && amazon.feed_product_type != null
                && !amazon.feed_product_type.Equals("jewelryfinding", StringComparison.OrdinalIgnoreCase)
                && !amazon.feed_product_type.Equals("wallet", StringComparison.OrdinalIgnoreCase)
                && !amazon.feed_product_type.Equals("accessory", StringComparison.OrdinalIgnoreCase)
                && !amazon.feed_product_type.Equals("fineother", StringComparison.OrdinalIgnoreCase)
                && !amazon.feed_product_type.Equals("piercingjewelry", StringComparison.OrdinalIgnoreCase)
                && !amazon.feed_product_type.Equals("cufflink", StringComparison.OrdinalIgnoreCase)
                //tittle
                && amazon.item_name != null
                && !amazon.item_name.Contains("baby", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("child", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("LogoArt", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("GAME DAY", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("LOGO", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Logo Art", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("MLB", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("NFL", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("University", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("College", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("AMPED", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Geometric Signet", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("NASCAR", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tampa Bay Lightning", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("CHANEL", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Charles & Colvard", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("New York", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Portland Timbers", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Montreal Impact", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tennessee Titans", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Colorado Rapids", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Philadelphia", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("San Jose Earthquakes", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("South Carolina", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Toronto", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Oakland Athletics", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Chicago White Sox", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Boston Red Sox", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Houston Astros", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Kansas City Royals", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Virginia TECH", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tampa Bay Rays", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("MINNESOTA TWINS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Detroit Tigers", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("BOSTON RED SOX", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Wake Forest", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("PITTSBURGH", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Miami", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Vegas Golden Knights", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Southern", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Kentucky", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Cincinnati Reds", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Chicago Cubs", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Michigan", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Seattle Mariners", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("San Francisco Giants", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Nebraska", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Miami Marlins", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Mississippi", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Kappa Alpha", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Texas Rangers", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Washington", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Arizona Diamondbacks", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Kansas", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Los Angeles", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Baltimore Orioles", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Louisville", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Alabama", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("TCU", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Ottawa Senators", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Houston State", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Nevada", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Cleveland", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Atlanta Braves", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Moissanite", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("U.S. Navy", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("North Carolina State", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Vegas Golden", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Georgia", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Louisiana", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("EDMONTON", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Indiana", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Baltimore", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tampa Bay", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Houston", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Iowa State", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Florida", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("CALGARY FLAMES", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Clemson", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("ST LOUIS CARDINALS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("CHICAGO BLACKHAWKS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("AUBURN", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Pittsburgh Penguins", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Swarovski", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Of Iowa", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("MONTREAL CANADIENS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Chevron", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Boise", StringComparison.OrdinalIgnoreCase)
                //Stuller
                && !amazon.item_name.Contains("Lab-Grown", StringComparison.OrdinalIgnoreCase)
                )
                .ToList();
        }

        public static List<AmazonJewelryDataFeedItemV3_Dto> filterPrice(List<AmazonJewelryDataFeedItemV3_Dto> input)
        {
            var filteredProducts = input.Where(p =>
            {
                decimal price;
                bool isValidPrice = decimal.TryParse(p.standard_price, out price);

                // Nếu không thể chuyển đổi giá từ chuỗi sang kiểu decimal, bỏ qua sản phẩm này
                if (!isValidPrice)
                    return false;

                return price <= 3500; // lấy ra sản phẩm giá dưới 3500$
            }).ToList();

            return filteredProducts;
        }

        public static bool filtersSKU(AmazonJewelryDataFeedItem p)
        {
            if (
                //feed_product_type
                !p.feed_product_type.Equals("jewelryfinding", StringComparison.OrdinalIgnoreCase)
                && !p.feed_product_type.Equals("wallet", StringComparison.OrdinalIgnoreCase)
                && !p.feed_product_type.Equals("accessory", StringComparison.OrdinalIgnoreCase)
                && !p.feed_product_type.Equals("fineother", StringComparison.OrdinalIgnoreCase)
                && !p.feed_product_type.Equals("piercingjewelry", StringComparison.OrdinalIgnoreCase)
                && !p.feed_product_type.Equals("cufflink", StringComparison.OrdinalIgnoreCase)

                 //tittle
                && !p.item_name.Contains("baby", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("child", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("LogoArt", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("GAME DAY", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("LOGO", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Logo Art", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("MLB", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("NFL", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("University", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("College", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("AMPED", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Geometric Signet", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("NASCAR", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Tampa Bay Lightning", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("CHANEL", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Charles & Colvard", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("New York", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Portland Timbers", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Montreal Impact", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Tennessee Titans", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Colorado Rapids", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Philadelphia Union", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("San Jose Earthquakes", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("South Carolina", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Toronto", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Oakland Athletics", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Chicago White Sox", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Boston Red Sox", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Houston Astros", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Kansas City Royals", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Virginia TECH", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Tampa Bay Rays", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("MINNESOTA TWINS", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Detroit Tigers", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("BOSTON RED SOX", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Wake Forest", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("PITTSBURGH", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("of Miami", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Vegas Golden Knights", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Southern", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("of Kentucky", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Cincinnati Reds", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Chicago Cubs", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("of Michigan", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Seattle Mariners", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("San Francisco Giants", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("of Nebraska", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Miami Marlins", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Mississippi", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Kappa Alpha", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Texas Rangers", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Washington", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Arizona Diamondbacks", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Kansas", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Los Angeles", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Baltimore Orioles", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Louisville", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Alabama", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("TCU", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Ottawa Senators", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Houston State", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Nevada", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Cleveland", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Atlanta Braves", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Moissanite", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("U.S. Navy", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("North Carolina State", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Vegas Golden", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Georgia", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Louisiana", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("EDMONTON", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Indiana", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Baltimore", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Tampa Bay", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Houston", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Iowa State", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Florida", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("CALGARY FLAMES", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Clemson", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("ST LOUIS CARDINALS", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("CHICAGO BLACKHAWKS", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("AUBURN", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Chevron", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Pittsburgh Penguins", StringComparison.OrdinalIgnoreCase)
                && !p.item_name.Contains("Swarovski", StringComparison.OrdinalIgnoreCase)
                && !p.product_description.Contains("Childrens", StringComparison.OrdinalIgnoreCase)
                //Stuller
                && !p.item_name.Contains("Lab-Grown", StringComparison.OrdinalIgnoreCase)
                )
            {
                return true;
            }
            return false;
        }


        public static bool filterPrice(AmazonJewelryDataFeedItem p)
        {
            decimal price;
            bool isValidPrice = decimal.TryParse(p.standard_price, out price);
            // Nếu không thể chuyển đổi giá từ chuỗi sang kiểu decimal, bỏ qua sản phẩm này
            if (!isValidPrice)
                return false;

            return price <= 3500; // lấy ra sản phẩm giá trên 3500$
        }
        public static List<AmazonJewelryDataFeedItemV3_Dto> filtersSKUSllerDelete(List<AmazonJewelryDataFeedItemV3_Dto> input)
        {
            return input.Where(amazon =>
                amazon.item_name != null && amazon.product_description != null
                && !amazon.item_name.Contains("baby", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("child", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("LogoArt", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("GAME DAY", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("LOGO", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Logo Art", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("MLB", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("NFL", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("University", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("College", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("AMPED", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Geometric Signet", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("NASCAR", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tampa Bay Lightning", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("CHANEL", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Charles & Colvard", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("New York", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Portland Timbers", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Montreal Impact", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tennessee Titans", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Colorado Rapids", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Philadelphia", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("San Jose Earthquakes", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("South Carolina", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Toronto", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Oakland Athletics", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Chicago White Sox", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Boston Red Sox", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Houston Astros", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Kansas City Royals", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Virginia TECH", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tampa Bay Rays", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("MINNESOTA TWINS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Detroit Tigers", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("BOSTON RED SOX", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Wake Forest", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("PITTSBURGH", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Miami", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Vegas Golden Knights", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Southern", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Kentucky", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Cincinnati Reds", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Chicago Cubs", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Michigan", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Seattle Mariners", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("San Francisco Giants", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("of Nebraska", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Miami Marlins", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Mississippi", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Kappa Alpha", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Texas Rangers", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Washington", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Arizona Diamondbacks", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Kansas", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Los Angeles", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Baltimore Orioles", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Louisville", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Alabama", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("TCU", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Ottawa Senators", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Houston State", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Nevada", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Cleveland", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Atlanta Braves", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Moissanite", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("U.S. Navy", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("North Carolina State", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Vegas Golden", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Georgia", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Louisiana", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("EDMONTON", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Indiana", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Baltimore", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Tampa Bay", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Houston", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Iowa State", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Florida", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("CALGARY FLAMES", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Clemson", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("ST LOUIS CARDINALS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("CHICAGO BLACKHAWKS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("AUBURN", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Pittsburgh Penguins", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Swarovski", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Of Iowa", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("MONTREAL CANADIENS", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Boise", StringComparison.OrdinalIgnoreCase)
                && !amazon.item_name.Contains("Chevron", StringComparison.OrdinalIgnoreCase)
                && !amazon.product_description.Contains("Childrens", StringComparison.OrdinalIgnoreCase)
                //Stuller
                && !amazon.item_name.Contains("Lab-Grown", StringComparison.OrdinalIgnoreCase)
                )
                .ToList();
        }
    }
}
