using StullerToAmazonDomain.Amazon;
using System.ComponentModel.DataAnnotations;

namespace AmazonIntegrationDataApi.Models
{
    public class AmazonJewelryDataFeedItemV3 : IAmazonJewelryDataFeedItem_v3
    {
        public  string? feed_product_type { get; set; }
        [Key]
        public string item_sku { get; set; }
        public  string? brand_name { get; set; }
        public  string? external_product_id { get; set; }
        public  string? external_product_id_type { get; set; }
        public  string? item_name { get; set; }
        public  string? item_length_numeric { get; set; }
        public  string? item_length_numeric_unit_of_measure { get; set; }
        public  string? main_image_url { get; set; }
        public  string? target_gender { get; set; }
        public  string? quantity { get; set; }
        public  string? standard_price { get; set; }
        public  string? item_type { get; set; }
        public  string? metal_type { get; set; }
        public  string? material_type1 { get; set; }
        public  string? material_type2 { get; set; }
        public  string? material_type3 { get; set; }
        public  string? material_type4 { get; set; }
        public  string? material_type5 { get; set; }
        public  string? department_name1 { get; set; }
        public  string? department_name2 { get; set; }
        public  string? department_name3 { get; set; }
        public  string? department_name4 { get; set; }
        public  string? department_name5 { get; set; }
        public  string? gem_type1 { get; set; }
        public  string? gem_type2 { get; set; }
        public  string? gem_type3 { get; set; }
        public  string? color_map { get; set; }
        public  string? size_name { get; set; }
        public  string? age_range_description { get; set; }
        public  string? manufacturer { get; set; }
        public  string? part_number { get; set; }
        public  string? model { get; set; }
        public  string? watch_movement_type { get; set; }
        public  string? target_audience_keywords1 { get; set; }
        public  string? target_audience_keywords2 { get; set; }
        public  string? target_audience_keywords3 { get; set; }
        public  string? target_audience_keywords4 { get; set; }
        public  string? target_audience_keywords5 { get; set; }
        public  string? display_type { get; set; }
        public  string? product_description { get; set; }
        public  string? model_name { get; set; }
        public  string? bullet_point1 { get; set; }
        public  string? bullet_point2 { get; set; }
        public  string? bullet_point3 { get; set; }
        public  string? bullet_point4 { get; set; }
        public  string? bullet_point5 { get; set; }
        public  string? bullet_point6 { get; set; }
        public  string? bullet_point7 { get; set; }
        public  string? bullet_point8 { get; set; }
        public  string? bullet_point9 { get; set; }
        public  string? bullet_point10 { get; set; }
        public  string? item_type_name { get; set; }
        public  string? number_of_boxes { get; set; }
        public  string? item_length_unit_of_measure { get; set; }
        public  string? item_height { get; set; }
        public  string? item_length { get; set; }
        public  string? item_width { get; set; }
        public  string? item_width_unit_of_measure { get; set; }
        public  string? item_height_unit_of_measure { get; set; }
        public  string? cpsia_cautionary_statement1 { get; set; }
        public  string? cpsia_cautionary_statement2 { get; set; }
        public  string? cpsia_cautionary_statement3 { get; set; }
        public  string? cpsia_cautionary_statement4 { get; set; }
        public  string? country_of_origin { get; set; }
        public  string? warranty_description { get; set; }
        public  string? condition_type { get; set; }
        public  string? currency { get; set; }
        public  string? number_of_items { get; set; }
        public  string? is_expiration_dated_product { get; set; }
        public  string? setting_type { get; set; }
        public  string? color_name { get; set; }
        public  string? ring_size { get; set; }
        public  string? depth_front_to_back { get; set; }
        public  string? depth_front_to_back_unit_of_measure { get; set; }
        public  string? depth_width_side_to_side { get; set; }
        public  string? depth_width_side_to_side_unit_of_measure { get; set; }
        public  string? depth_height_floor_to_top { get; set; }
        public  string? depth_height_floor_to_top_unit_of_measure { get; set; }
        public  string? package_height { get; set; }
        public  string? package_width { get; set; }
        public  string? package_length { get; set; }
        public  string? package_length_unit_of_measure { get; set; }
        public  string? package_weight { get; set; }
        public  string? package_weight_unit_of_measure { get; set; }
        public  string? package_height_unit_of_measure { get; set; }
        public  string? package_width_unit_of_measure { get; set; }
        public  string? supplier_declared_dg_hz_regulation1 { get; set; }
        public  string? supplier_declared_dg_hz_regulation2 { get; set; }
        public  string? supplier_declared_dg_hz_regulation3 { get; set; }
        public  string? supplier_declared_dg_hz_regulation4 { get; set; }
        public  string? supplier_declared_dg_hz_regulation5 { get; set; }
        public  string? supplier_declared_material_regulation1 { get; set; }
        public  string? supplier_declared_material_regulation2 { get; set; }
        public  string? supplier_declared_material_regulation3 { get; set; }
        public  string? lifecycle_supply_type { get; set; }
        public  string? map_price { get; set; }
        public  string? style_name { get; set; }
        public  string? unit_count { get; set; }
        public  string? unit_count_type { get; set; }
        public  string? closure_type { get; set; }
        public  string? care_instructions { get; set; }
        public  string? fabric_type1 { get; set; }
        public  string? fabric_type2 { get; set; }
        public  string? fabric_type3 { get; set; }
        public  string? fabric_type4 { get; set; }
        public  string? fabric_type5 { get; set; }
        public  string? fabric_type6 { get; set; }
        public  string? fabric_type7 { get; set; }
        public  string? fabric_type8 { get; set; }
        public  string? fabric_type9 { get; set; }
        public  string? fabric_type10 { get; set; }
        public  string? import_designation { get; set; }
        public  string? generic_keywords { get; set; }
        public  string? outer_material_type1 { get; set; }
        public  string? outer_material_type2 { get; set; }
        public  string? outer_material_type3 { get; set; }
        public  string? outer_material_type4 { get; set; }
        public  string? outer_material_type5 { get; set; }
        public  string? material_composition { get; set; }
        public  string? size_map { get; set; }
        public  string? other_image_url1 { get; set; }
        public  string? other_image_url2 { get; set; }
        public  string? other_image_url3 { get; set; }
        public  string? other_image_url4 { get; set; }
        public  string? other_image_url5 { get; set; }
        public  string? other_image_url6 { get; set; }
        public  string? other_image_url7 { get; set; }
        public  string? other_image_url8 { get; set; }
        public  string? swatch_image_url { get; set; }
        public  string? pt8_image_url { get; set; }
        public  string? pt7_image_url { get; set; }
        public  string? pt5_image_url { get; set; }
        public  string? pt4_image_url { get; set; }
        public  string? pt3_image_url { get; set; }
        public  string? pt2_image_url { get; set; }
        public  string? pt6_image_url { get; set; }
        public  string? pt1_image_url { get; set; }
        public  string? relationship_type { get; set; }
        public  string? variation_theme { get; set; }
        public  string? package_level { get; set; }
        public  string? parent_sku { get; set; }
        public  string? package_contains_quantity { get; set; }
        public  string? package_contains_identifier { get; set; }
        public  string? parent_child { get; set; }
        public  string? update_delete { get; set; }
        public  string? certificate_number1 { get; set; }
        public  string? certificate_number2 { get; set; }
        public  string? certificate_number3 { get; set; }
        public  string? certificate_number4 { get; set; }
        public  string? certificate_number5 { get; set; }
        public  string? certificate_number6 { get; set; }
        public  string? certificate_number7 { get; set; }
        public  string? certificate_number8 { get; set; }
        public  string? certificate_number9 { get; set; }
        public  string? grade_rating { get; set; }
        public  string? certificate_type1 { get; set; }
        public  string? certificate_type2 { get; set; }
        public  string? certificate_type3 { get; set; }
        public  string? certificate_type4 { get; set; }
        public  string? certificate_type5 { get; set; }
        public  string? certificate_type6 { get; set; }
        public  string? certificate_type7 { get; set; }
        public  string? certificate_type8 { get; set; }
        public  string? certificate_type9 { get; set; }
        public  string? model_year { get; set; }
        public  string? inner_material_type { get; set; }
        public  string? gtin_exemption_reason { get; set; }
        public  string? production_method { get; set; }
        public  string? stone_color1 { get; set; }
        public  string? stone_color2 { get; set; }
        public  string? stone_color3 { get; set; }
        public  string? metals_metal_weight_unit_of_measure { get; set; }
        public  string? stones_color { get; set; }
        public  string? occasion_type1 { get; set; }
        public  string? occasion_type2 { get; set; }
        public  string? occasion_type3 { get; set; }
        public  string? occasion_type4 { get; set; }
        public  string? occasion_type5 { get; set; }
        public  string? clasp_type { get; set; }
        public  string? stones_id { get; set; }
        public  string? stones_creation_method { get; set; }
        public  string? athlete { get; set; }
        public  string? team_name { get; set; }
        public  string? stone_shape1 { get; set; }
        public  string? stone_shape2 { get; set; }
        public  string? stone_shape3 { get; set; }
        public  string? stone_clarity1 { get; set; }
        public  string? stone_clarity2 { get; set; }
        public  string? stone_clarity3 { get; set; }
        public  string? collection_name { get; set; }
        public  string? metals_metal_weight { get; set; }
        public  string? metals_metal_type { get; set; }
        public  string? stones_type { get; set; }
        public  string? stones_clarity { get; set; }
        public  string? stones_number_of_stones { get; set; }
        public  string? stones_treatment_method { get; set; }
        public  string? fur_description { get; set; }
        public  string? metals_id { get; set; }
        public  string? initial_character { get; set; }
        public  string? metals_metal_stamp { get; set; }
        public  string? stones_shape { get; set; }
        public  string? chain_length_unit { get; set; }
        public  string? stones_cut { get; set; }
        public  string? stone_cut1 { get; set; }
        public  string? stone_cut2 { get; set; }
        public  string? stone_cut3 { get; set; }
        public  string? league_name { get; set; }
        public  string? thesaurus_subject_keywords1 { get; set; }
        public  string? thesaurus_subject_keywords2 { get; set; }
        public  string? thesaurus_subject_keywords3 { get; set; }
        public  string? thesaurus_subject_keywords4 { get; set; }
        public  string? thesaurus_subject_keywords5 { get; set; }
        public  string? chain_length_derived { get; set; }
        public  string? chain_type { get; set; }
        public  string? item_booking_date { get; set; }
        public  string? drop_length_unit { get; set; }
        public  string? back_finding { get; set; }
        public  string? drop_length { get; set; }
        public  string? is_autographed { get; set; }
        public  string? sport_type1 { get; set; }
        public  string? sport_type2 { get; set; }
        public  string? sport_type3 { get; set; }
        public  string? seasons1 { get; set; }
        public  string? seasons2 { get; set; }
        public  string? seasons3 { get; set; }
        public  string? seasons4 { get; set; }
        public  string? lifestyle { get; set; }
        public  string? fit_type1 { get; set; }
        public  string? fit_type2 { get; set; }
        public  string? fit_type3 { get; set; }
        public  string? fit_type4 { get; set; }
        public  string? fit_type5 { get; set; }
        public  string? weave_type { get; set; }
        public  string? theme { get; set; }
        public  string? special_size_type { get; set; }
        public  string? thesaurus_attribute_keywords1 { get; set; }
        public  string? thesaurus_attribute_keywords2 { get; set; }
        public  string? thesaurus_attribute_keywords3 { get; set; }
        public  string? thesaurus_attribute_keywords4 { get; set; }
        public  string? thesaurus_attribute_keywords5 { get; set; }
        public  string? catalog_number { get; set; }
        public  string? specific_uses_keywords1 { get; set; }
        public  string? specific_uses_keywords2 { get; set; }
        public  string? specific_uses_keywords3 { get; set; }
        public  string? specific_uses_keywords4 { get; set; }
        public  string? specific_uses_keywords5 { get; set; }
        public  string? band_material_type { get; set; }
        public  string? case_thickness { get; set; }
        public  string? band_color { get; set; }
        public  string? case_material_type { get; set; }
        public  string? water_resistance_depth { get; set; }
        public  string? water_resistance_depth_unit_of_measure { get; set; }
        public  string? platinum_keywords1 { get; set; }
        public  string? platinum_keywords2 { get; set; }
        public  string? platinum_keywords3 { get; set; }
        public  string? platinum_keywords4 { get; set; }
        public  string? platinum_keywords5 { get; set; }
        public  string? special_features1 { get; set; }
        public  string? special_features2 { get; set; }
        public  string? special_features3 { get; set; }
        public  string? special_features4 { get; set; }
        public  string? special_features5 { get; set; }
        public  string? band_length { get; set; }
        public  string? operating_system { get; set; }
        public  string? case_thickness_unit_of_measure { get; set; }
        public  string? supported_application { get; set; }
        public  string? target_audience_base1 { get; set; }
        public  string? target_audience_base2 { get; set; }
        public  string? target_audience_base3 { get; set; }
        public  string? target_audience_base4 { get; set; }
        public  string? target_audience_base5 { get; set; }
        public  string? band_length_unit { get; set; }
        public  string? water_resistance_level { get; set; }
        public  string? directions { get; set; }
        public  string? paint_type { get; set; }
        public  string? number_of_pieces { get; set; }
        public  string? is_assembly_required { get; set; }
        public  string? included_components1 { get; set; }
        public  string? included_components2 { get; set; }
        public  string? included_components3 { get; set; }
        public  string? included_components4 { get; set; }
        public  string? included_components5 { get; set; }
        public  string? is_resizable { get; set; }
        public  string? stone_creation_method1 { get; set; }
        public  string? stone_creation_method2 { get; set; }
        public  string? stone_creation_method3 { get; set; }
        public  string? stone_treatment_method1 { get; set; }
        public  string? stone_treatment_method2 { get; set; }
        public  string? stone_treatment_method3 { get; set; }
        public  string? gauge_derived { get; set; }
        public  string? lining_description { get; set; }
        public  string? number_of_compartments { get; set; }
        public  string? number_of_wheels { get; set; }
        public  string? pattern_name { get; set; }
        public  string? wheel_type { get; set; }
        public  string? band_thickness { get; set; }
        public  string? band_thickness_unit_of_measure { get; set; }
        public  string? horsepower { get; set; }
        public  string? horsepower_unit_of_measure { get; set; }
        public  string? power_source_type { get; set; }
        public  string? voltage_unit_of_measure { get; set; }
        public  string? controller_type { get; set; }
        public  string? maximum_operating_pressure { get; set; }
        public  string? maximum_operating_pressure_unit_of_measure { get; set; }
        public  string? handle_location { get; set; }
        public  string? light_source_type { get; set; }
        public  string? brightness_unit_of_measure { get; set; }
        public  string? speed_unit_of_measure { get; set; }
        public  string? item_torque { get; set; }
        public  string? item_torque_unit_of_measure { get; set; }
        public  string? insulation_resistance_unit_of_measure { get; set; }
        public  string? mounting_type { get; set; }
        public  string? number_of_teeth { get; set; }
        public  string? oem_equivalent_part_number { get; set; }
        public  string? recommended_uses_for_product { get; set; }
        public  string? shank_type { get; set; }
        public  string? number_of_drawers { get; set; }
        public  string? belt_style { get; set; }
        public  string? embellishment_feature1 { get; set; }
        public  string? embellishment_feature2 { get; set; }
        public  string? embellishment_feature3 { get; set; }
        public  string? embellishment_feature4 { get; set; }
        public  string? embellishment_feature5 { get; set; }
        public  string? style_keywords1 { get; set; }
        public  string? style_keywords2 { get; set; }
        public  string? style_keywords3 { get; set; }
        public  string? compatible_devices { get; set; }
        public  string? front_style { get; set; }
        public  string? country_as_labeled { get; set; }
        public  string? neck_style { get; set; }
        public  string? pattern_type { get; set; }
        public  string? pocket_description { get; set; }
        public  string? shaft_style_type { get; set; }
        public  string? pearl_type { get; set; }
        public  string? legal_compliance_certification_certifying_authority_name { get; set; }
        public  string? pearl_uniformity { get; set; }
        public  string? pearl_shape { get; set; }
        public  string? pearl_surface_blemishes { get; set; }
        public  string? pearl_lustre { get; set; }
        public  string? legal_compliance_certification_geographic_jurisdiction { get; set; }
        public  string? flash_point_unit_of_measure { get; set; }
        public  string? pearl_stringing_method { get; set; }
        public  string? pearl_minimum_color { get; set; }
        public  string? inscription { get; set; }
        public  string? number_of_pearls { get; set; }
        public  string? number_of_stones { get; set; }
        public  string? duration_unit_of_measure { get; set; }
        public  string? subject_character { get; set; }
        public  string? duration { get; set; }
        public  string? sub_brand_name { get; set; }
        public  string? sleeve_type { get; set; }
        public  string? fabric_wash { get; set; }
        public  string? designer { get; set; }
        public  string? band_size { get; set; }
        public  string? dial_color { get; set; }
        public  string? bezel_material_type { get; set; }
        public  string? bezel_function { get; set; }
        public  string? dial_window_material_type { get; set; }
        public  string? calendar_type { get; set; }
        public  string? resale_type { get; set; }
        public  string? authenticated_by { get; set; }
        public  string? finish_type1 { get; set; }
        public  string? finish_type2 { get; set; }
        public  string? fc_shelf_life_unit_of_measure { get; set; }
        public  string? ring_sizing_lower_range { get; set; }
        public  string? ring_sizing_upper_range { get; set; }
        public  string? golf_club_flex { get; set; }
        public  string? connectivity_protocol { get; set; }
        public  string? item_pitch_unit_of_measure { get; set; }
        public  string? energy_guide_cost_disclosure { get; set; }
        public  string? is_oem_authorized { get; set; }
        public  string? energy_guide_annual_operating_cost { get; set; }
        public  string? belt_width_unit_of_measure { get; set; }
        public  string? belt_width_string { get; set; }
        public  string? opacity_unit_of_measure { get; set; }
        public  string? map_policy { get; set; }
        public  string? belt_width_derived { get; set; }
        public  string? index_suppressed { get; set; }
        public  string? leg_style { get; set; }
        public  string? opacity { get; set; }
        public  string? strap_type { get; set; }
        public  string? underwire_type { get; set; }
        public  string? item_display_weight { get; set; }
        public  string? total_diamond_weight { get; set; }
        public  string? item_display_diameter { get; set; }
        public  string? stone_weight1 { get; set; }
        public  string? stone_weight2 { get; set; }
        public  string? stone_weight3 { get; set; }
        public  string? stone_weight_unit_of_measure1 { get; set; }
        public  string? stone_weight_unit_of_measure2 { get; set; }
        public  string? stone_weight_unit_of_measure3 { get; set; }
        public  string? total_gem_weight { get; set; }
        public  string? size_per_pearl { get; set; }
        public  string? item_display_diameter_unit_of_measure { get; set; }
        public  string? item_display_length { get; set; }
        public  string? item_display_length_unit_of_measure { get; set; }
        public  string? total_gem_weight_unit_of_measure { get; set; }
        public  string? item_display_weight_unit_of_measure { get; set; }
        public  string? total_diamond_weight_unit_of_measure { get; set; }
        public  string? band_width { get; set; }
        public  string? band_width_unit_of_measure { get; set; }
        public  string? case_diameter { get; set; }
        public  string? case_diameter_unit_of_measure { get; set; }
        public  string? item_shape { get; set; }
        public  string? website_shipping_weight { get; set; }
        public  string? website_shipping_weight_unit_of_measure { get; set; }
        public  string? maximum_size { get; set; }
        public  string? maximum_size_unit_of_measure { get; set; }
        public  string? line_size { get; set; }
        public  string? line_size_unit_of_measure { get; set; }
        public  string? paper_size { get; set; }
        public  string? paper_size_unit_of_measure { get; set; }
        public  string? item_display_height { get; set; }
        public  string? item_display_width { get; set; }
        public  string? stone_dimensions_unit_of_measure1 { get; set; }
        public  string? stone_dimensions_unit_of_measure2 { get; set; }
        public  string? stone_dimensions_unit_of_measure3 { get; set; }
        public  string? item_display_height_unit_of_measure { get; set; }
        public  string? item_display_width_unit_of_measure { get; set; }
        public  string? total_metal_weight { get; set; }
        public  string? total_metal_weight_unit_of_measure { get; set; }
        public  string? stone_width_unit_of_measure1 { get; set; }
        public  string? stone_width_unit_of_measure2 { get; set; }
        public  string? stone_width_unit_of_measure3 { get; set; }
        public  string? stone_width1 { get; set; }
        public  string? stone_width2 { get; set; }
        public  string? stone_width3 { get; set; }
        public  string? measurement_system { get; set; }
        public  string? item_diameter_derived { get; set; }
        public  string? item_diameter_unit_of_measure { get; set; }
        public  string? maximum_weight_recommendation_unit_of_measure { get; set; }
        public  string? maximum_weight_recommendation { get; set; }
        public  string? stone_length1 { get; set; }
        public  string? stone_length2 { get; set; }
        public  string? stone_length3 { get; set; }
        public  string? stone_length_unit_of_measure1 { get; set; }
        public  string? stone_length_unit_of_measure2 { get; set; }
        public  string? stone_length_unit_of_measure3 { get; set; }
        public  string? stone_height1 { get; set; }
        public  string? stone_height2 { get; set; }
        public  string? stone_height3 { get; set; }
        public  string? item_thickness_unit_of_measure { get; set; }
        public  string? item_thickness_derived { get; set; }
        public  string? band_size_num { get; set; }
        public  string? band_size_num_unit_of_measure { get; set; }
        public  string? leg_diameter { get; set; }
        public  string? leg_diameter_unit_of_measure { get; set; }
        public  string? neck_size { get; set; }
        public  string? neck_size_unit_of_measure { get; set; }
        public  string? shoe_width { get; set; }
        public  string? waist_size { get; set; }
        public  string? waist_size_unit_of_measure { get; set; }
        public  string? shoe_width_unit_of_measure { get; set; }
        public  string? fulfillment_center_id { get; set; }
        public  string? regulation_type1 { get; set; }
        public  string? regulation_type2 { get; set; }
        public  string? regulation_type3 { get; set; }
        public  string? regulation_type4 { get; set; }
        public  string? regulation_type5 { get; set; }
        public  string? regulatory_compliance_certification_value1 { get; set; }
        public  string? regulatory_compliance_certification_value2 { get; set; }
        public  string? regulatory_compliance_certification_value3 { get; set; }
        public  string? regulatory_compliance_certification_value4 { get; set; }
        public  string? regulatory_compliance_certification_value5 { get; set; }
        public  string? batteries_required { get; set; }
        public  string? are_batteries_included { get; set; }
        public  string? battery_cell_composition { get; set; }
        public  string? battery_type1 { get; set; }
        public  string? battery_type2 { get; set; }
        public  string? battery_type3 { get; set; }
        public  string? number_of_batteries1 { get; set; }
        public  string? number_of_batteries2 { get; set; }
        public  string? number_of_batteries3 { get; set; }
        public  string? battery_weight { get; set; }
        public  string? battery_weight_unit_of_measure { get; set; }
        public  string? number_of_lithium_metal_cells { get; set; }
        public  string? number_of_lithium_ion_cells { get; set; }
        public  string? lithium_battery_packaging { get; set; }
        public  string? lithium_battery_energy_content { get; set; }
        public  string? lithium_battery_energy_content_unit_of_measure { get; set; }
        public  string? lithium_battery_weight { get; set; }
        public  string? lithium_battery_weight_unit_of_measure { get; set; }
        public  string? hazmat_united_nations_regulatory_id { get; set; }
        public  string? safety_data_sheet_url { get; set; }
        public  string? item_weight { get; set; }
        public  string? item_weight_unit_of_measure { get; set; }
        public  string? item_volume { get; set; }
        public  string? item_volume_unit_of_measure { get; set; }
        public  string? warranty_type { get; set; }
        public  string? legal_compliance_certification_expiration_date { get; set; }
        public  string? legal_compliance_certification_regulatory_organization_name { get; set; }
        public  string? legal_compliance_certification_status { get; set; }
        public  string? flash_point { get; set; }
        public  string? legal_compliance_certification_date_of_issue { get; set; }
        public  string? legal_compliance_certification_metadata { get; set; }
        public  string? legal_compliance_certification_value { get; set; }
        public  string? metal_stamp { get; set; }
        public  string? ghs_classification_class1 { get; set; }
        public  string? ghs_classification_class2 { get; set; }
        public  string? ghs_classification_class3 { get; set; }
        public  string? california_proposition_65_compliance_type { get; set; }
        public  string? california_proposition_65_chemical_names1 { get; set; }
        public  string? california_proposition_65_chemical_names2 { get; set; }
        public  string? california_proposition_65_chemical_names3 { get; set; }
        public  string? california_proposition_65_chemical_names4 { get; set; }
        public  string? california_proposition_65_chemical_names5 { get; set; }
        public  string? pesticide_marking_type1 { get; set; }
        public  string? pesticide_marking_type2 { get; set; }
        public  string? pesticide_marking_type3 { get; set; }
        public  string? pesticide_marking_registration_status1 { get; set; }
        public  string? pesticide_marking_registration_status2 { get; set; }
        public  string? pesticide_marking_registration_status3 { get; set; }
        public  string? pesticide_marking_certification_number1 { get; set; }
        public  string? pesticide_marking_certification_number2 { get; set; }
        public  string? pesticide_marking_certification_number3 { get; set; }
        public  string? fcc_radio_frequency_emission_compliance_registration_status { get; set; }
        public  string? fcc_radio_frequency_emission_compliance_point_of_contact_email { get; set; }
        public  string? fcc_radio_frequency_emission_compliance_point_of_contact_phone_number { get; set; }
        public  string? fcc_radio_frequency_emission_compliance_point_of_contact_name { get; set; }
        public  string? fcc_radio_frequency_emission_compliance_identification_number { get; set; }
        public  string? fcc_radio_frequency_emission_compliance_point_of_contact_address { get; set; }
        public  string? cpsia_cautionary_description { get; set; }
        public  string? specific_uses_for_product1 { get; set; }
        public  string? specific_uses_for_product2 { get; set; }
        public  string? merchant_release_date { get; set; }
        public  string? list_price { get; set; }
        public  string? restock_date { get; set; }
        public  string? fulfillment_latency { get; set; }
        public  string? offering_can_be_giftwrapped { get; set; }
        public  string? item_package_quantity { get; set; }
        public  string? offering_end_date { get; set; }
        public  string? max_order_quantity { get; set; }
        public  string? merchant_shipping_group_name { get; set; }
        public  string? offering_start_date { get; set; }
        public  string? product_tax_code { get; set; }
        public  string? offering_can_be_gift_messaged { get; set; }
        public  string? condition_note { get; set; }
        public  string? sale_price { get; set; }
        public  string? sale_from_date { get; set; }
        public  string? sale_end_date { get; set; }
        public  string? product_site_launch_date { get; set; }
        public  string? max_aggregate_ship_quantity { get; set; }
        public  string? is_discontinued_by_manufacturer { get; set; }
        public  string? delivery_schedule_group_id { get; set; }
        public  string? product_expiration_type { get; set; }
        public  string? fc_shelf_life { get; set; }
        public  string? business_price { get; set; }
        public  string? quantity_price_type { get; set; }
        public  string? quantity_lower_bound1 { get; set; }
        public  string? quantity_price1 { get; set; }
        public  string? quantity_lower_bound2 { get; set; }
        public  string? quantity_price2 { get; set; }
        public  string? quantity_lower_bound3 { get; set; }
        public  string? quantity_price3 { get; set; }
        public  string? quantity_lower_bound4 { get; set; }
        public  string? quantity_price4 { get; set; }
        public  string? quantity_lower_bound5 { get; set; }
        public  string? quantity_price5 { get; set; }
        public  string? progressive_discount_type { get; set; }
        public  string? progressive_discount_lower_bound1 { get; set; }
        public  string? progressive_discount_value1 { get; set; }
        public  string? progressive_discount_lower_bound2 { get; set; }
        public  string? progressive_discount_value2 { get; set; }
        public  string? progressive_discount_lower_bound3 { get; set; }
        public  string? progressive_discount_value3 { get; set; }
        public  string? national_stock_number { get; set; }
        public  string? unspsc_code { get; set; }
        public  string? pricing_action { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }

    }
    public class AmazonJewelryDataForUpdate
    {
        public string item_sku { get; set; }
        public string quantity { get; set; }
        public string standard_price { get; set; }
    }
}
